# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Sight.create(name: "Iron Sights")
Sight.create(name: "Red Dot Sight")
Sight.create(name: "Holographic Sight")
Sight.create(name: "Reflex Sight")
Sight.create(name: "ACOG Sight")

Barrel.create(name: "Suppressor")
Barrel.create(name: "Flash Hider")
Barrel.create(name: "Compensator")
Barrel.create(name: "Muzzle Break")
Barrel.create(name: "Long Barrel")
Barrel.create(name: "None")

Grip.create(name: "Vertical Grip")
Grip.create(name: "Angled Grip")
Grip.create(name: "None")

Utility.create(name: "Breach Charges", attacker: true)
Utility.create(name: "Frag Grenades", attacker: true)
Utility.create(name: "Smoke Grenades", attacker: true)
Utility.create(name: "Stun Grenades", attacker: true)
Utility.create(name: "Claymore", attacker: true)

Utility.create(name: "Barbed Wire", attacker: false)
Utility.create(name: "Deployable Shield", attacker: false)
Utility.create(name: "Nitro Cell", attacker: false)
Utility.create(name: "Impact Grenades", attacker: false)
Utility.create(name: "Bulletproof Camera", attacker: false)

Gadget.create(name: "Breaching Hammer", attacker: true)
Gadget.create(name: "EG MKO-EMP Gernades", attacker: true)
Gadget.create(name: "Toxic Babes", attacker: false)
Gadget.create(name: "GC90 Signal Disrupters", attacker: false)
Gadget.create(name: "M120 CREM Breaching Rounds", attacker: true)
Gadget.create(name: "Brmistone BC-3 Exothermic Charges", attacker: true)
Gadget.create(name: "Armor Panels", attacker: false)
Gadget.create(name: "Cardiac Sensor", attacker: false)
Gadget.create(name: "Shock Drones", attacker: true)
Gadget.create(name: "Extendable Shield", attacker: true)
Gadget.create(name: "MPD-0 Stim Pistol", attacker: false)
Gadget.create(name: "R1N Armor Plates", attacker: false)
Gadget.create(name: "HDS Flip Sight", attacker: true)
Gadget.create(name: "APM-6 Cluster Charges", attacker: true)
Gadget.create(name: "EDD MKII Tripwires", attacker: false)
Gadget.create(name: "RP-46 Degtyaryov Machine Gun", attacker: false)
Gadget.create(name: "G52-Tactical Shield", attacker: true)
Gadget.create(name: "RED Mk III Electronics Detector", attacker: true)
Gadget.create(name: "Active Defense Systems", attacker: false)
Gadget.create(name: "Shock Wires", attacker: false)
Gadget.create(name: "Skeleton Key", attacker: true)
Gadget.create(name: "Welcome Mats", attacker: false)
Gadget.create(name: "Mounted Rifle Shields", attacker: true)
Gadget.create(name: "Black Eye Cameras", attacker: false)
Gadget.create(name: "Tactical Crossbow", attacker: true)
Gadget.create(name: "Silent Step", attacker: false)
Gadget.create(name: "X-KAIROS", attacker: true)
Gadget.create(name: "Yokai Drones", attacker: false)
Gadget.create(name: "Eyenox Model III", attacker: true)
Gadget.create(name: "Black Mirrors", attacker: false)
Gadget.create(name: "Candelas", attacker: true)
Gadget.create(name: "Gu Mines", attacker: false)
Gadget.create(name: "KS79 LIFELINE", attacker: true)
Gadget.create(name: "Grzmot Mines", attacker: false)
Gadget.create(name: "Logic Bombs", attacker: true)
Gadget.create(name: "ERC-7 Video Disruptor", attacker: false)
Gadget.create(name: "EE-ONE-D", attacker: true)
Gadget.create(name: "Adrenal Surges", attacker: true)
Gadget.create(name: "Evil Eyes", attacker: false)
Gadget.create(name: "Prisma Decoys", attacker: false)
Gadget.create(name: "Breaching Torch", attacker: true)
Gadget.create(name: "CCE Shield", attacker: false)
Gadget.create(name: "Air Jabs", attacker: true)
Gadget.create(name: "Electroclaws", attacker: false)
Gadget.create(name: "Trax Stingers", attacker: true)
Gadget.create(name: "Pest Launcher", attacker: false)
Gadget.create(name: "HEL Presence Reduction", attacker: true)
Gadget.create(name: "Glance Smart Glasses", attacker: false)
Gadget.create(name: "Garra Hook", attacker: true)
Gadget.create(name: "Volcan Shields", attacker: false)
Gadget.create(name: "LV Explosive Lances", attacker: true)
Gadget.create(name: "Mag-NET", attacker: false)
