# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Sight.create(name: "Iron Sights")
Sight.create(name: "Red Dot Sight")
Sight.create(name: "Holographic Sight")
Sight.create(name: "Reflex Sight")
Sight.create(name: "ACOG Sight")

Barrel.create(name: "Suppressor")
Barrel.create(name: "Flash Hider")
Barrel.create(name: "Compensator")
Barrel.create(name: "Muzzle Break")
Barrel.create(name: "Long Barrel")
Barrel.create(name: "None")

Grip.create(name: "Vertical Grip")
Grip.create(name: "Angled Grip")
Grip.create(name: "None")

Utility.create(name: "Breach Charges", attacker: true)
Utility.create(name: "Frag Grenades", attacker: true)
Utility.create(name: "Smoke Grenades", attacker: true)
Utility.create(name: "Stun Grenades", attacker: true)
Utility.create(name: "Claymore", attacker: true)

Utility.create(name: "Barbed Wire", attacker: false)
Utility.create(name: "Deployable Shield", attacker: false)
Utility.create(name: "Nitro Cell", attacker: false)
Utility.create(name: "Impact Grenades", attacker: false)
Utility.create(name: "Bulletproof Camera", attacker: false)

Gadget.create(name: "Breaching Hammer", attacker: true)
Gadget.create(name: "EG MKO-EMP Gernades", attacker: true)
Gadget.create(name: "Toxic Babes", attacker: false)
Gadget.create(name: "GC90 Signal Disrupters", attacker: false)
Gadget.create(name: "M120 CREM Breaching Rounds", attacker: true)
Gadget.create(name: "Brmistone BC-3 Exothermic Charges", attacker: true)
Gadget.create(name: "Armor Panels", attacker: false)
Gadget.create(name: "Cardiac Sensor", attacker: false)
Gadget.create(name: "Shock Drones", attacker: true)
Gadget.create(name: "Extendable Shield", attacker: true)
Gadget.create(name: "Extendable Shield", attacker: false)
Gadget.create(name: "MPD-0 Stim Pistol", attacker: false)
Gadget.create(name: "R1N Armor Plates", attacker: false)
Gadget.create(name: "HDS Flip Sight", attacker: true)
Gadget.create(name: "APM-6 Cluster Charges", attacker: true)
Gadget.create(name: "EDD MKII Tripwires", attacker: false)
Gadget.create(name: "RP-46 Degtyaryov Machine Gun", attacker: false)
Gadget.create(name: "G52-Tactical Shield", attacker: true)
Gadget.create(name: "RED Mk III Electronics Detector", attacker: true)
Gadget.create(name: "Active Defense Systems", attacker: false)
Gadget.create(name: "Shock Wires", attacker: false)
Gadget.create(name: "Skeleton Key", attacker: true)
Gadget.create(name: "Welcome Mats", attacker: false)
Gadget.create(name: "Mounted Rifle Shields", attacker: true)
Gadget.create(name: "Black Eye Cameras", attacker: false)
Gadget.create(name: "Tactical Crossbow", attacker: true)
Gadget.create(name: "Silent Step", attacker: false)
Gadget.create(name: "X-KAIROS", attacker: true)
Gadget.create(name: "Yokai Drones", attacker: false)
Gadget.create(name: "Eyenox Model III", attacker: true)
Gadget.create(name: "Black Mirrors", attacker: false)
Gadget.create(name: "Candelas", attacker: true)
Gadget.create(name: "Gu Mines", attacker: false)
Gadget.create(name: "KS79 LIFELINE", attacker: true)
Gadget.create(name: "Grzmot Mines", attacker: false)
Gadget.create(name: "Logic Bombs", attacker: true)
Gadget.create(name: "ERC-7 Video Disruptor", attacker: false)
Gadget.create(name: "EE-ONE-D", attacker: true)
Gadget.create(name: "Adrenal Surges", attacker: true)
Gadget.create(name: "Evil Eyes", attacker: false)
Gadget.create(name: "Prisma Decoys", attacker: false)
Gadget.create(name: "Breaching Torch", attacker: true)
Gadget.create(name: "CCE Shield", attacker: false)
Gadget.create(name: "Air Jabs", attacker: true)
Gadget.create(name: "Electroclaws", attacker: false)
Gadget.create(name: "Trax Stingers", attacker: true)
Gadget.create(name: "Pest Launcher", attacker: false)
Gadget.create(name: "HEL Presence Reduction", attacker: true)
Gadget.create(name: "Glance Smart Glasses", attacker: false)
Gadget.create(name: "Garra Hook", attacker: true)
Gadget.create(name: "Volcan Shields", attacker: false)
Gadget.create(name: "LV Explosive Lances", attacker: true)
Gadget.create(name: "Mag-NET", attacker: false)

Weapon.create(name: ".44 Mag Semi-Auto", primary: false)
Weapon.create(name: "M1014", primary: true)
Weapon.create(name: "1911 TACOPS", primary: false)
Weapon.create(name: "416-C Carbine", primary: true)
Weapon.create(name: "M12", primary: true)
Weapon.create(name: "Mk 14 EBR", primary: true)
Weapon.create(name: "M249", primary: true)
Weapon.create(name: "Super 90", primary: true)
Weapon.create(name: "M4", primary: true)
Weapon.create(name: "417", primary: true)
Weapon.create(name: "M45 MEUSOC", primary: false)
Weapon.create(name: "M590A1", primary: true)
Weapon.create(name: "M762", primary: true)
Weapon.create(name: "M870", primary: true)
Weapon.create(name: "SMG-11", primary: false)
Weapon.create(name: "Mk1 9mm", primary: false)
Weapon.create(name: "MP5", primary: true)
Weapon.create(name: "MP5K", primary: true)
Weapon.create(name: "MP5SD", primary: true)
Weapon.create(name: "MP7", primary: true)
Weapon.create(name: "SPSMG9", primary: false)
Weapon.create(name: "MPX", primary: true)
Weapon.create(name: "Mx4 Storm", primary: true)
Weapon.create(name: "OTs-03", primary: true)
Weapon.create(name: "P-10C", primary: false)
Weapon.create(name: "P10 RONI", primary: true)
Weapon.create(name: "P12", primary: false)
Weapon.create(name: "P226 Mk 25", primary: false)
Weapon.create(name: "P229", primary: false)
Weapon.create(name: "P9", primary: false)
Weapon.create(name: "P90", primary: true)
Weapon.create(name: "PARA-308", primary: true)
Weapon.create(name: "PDW9", primary: true)
Weapon.create(name: "PMM", primary: false)
Weapon.create(name: "Q-929", primary: false)
Weapon.create(name: "R4-C", primary: true)
Weapon.create(name: "RG-15", primary: false)
Weapon.create(name: "SASG-12", primary: true)
Weapon.create(name: "Mk17 CQB", primary: true)
Weapon.create(name: "Scorpion EVO 3 A1", primary: true)
Weapon.create(name: "SDP 9mm", primary: false)
Weapon.create(name: "SG-CQB", primary: true)
Weapon.create(name: "SIX12", primary: true)
Weapon.create(name: "SMG-12", primary: false)
Weapon.create(name: "SPAS-12", primary: true)
Weapon.create(name: "SPAS-15", primary: true)
Weapon.create(name: "Spear .308", primary: true)
Weapon.create(name: "SR-25", primary: true)
Weapon.create(name: "Super Shorty", primary: false)
Weapon.create(name: "SuperNova", primary: true)
Weapon.create(name: "T-5 SMG", primary: true)
Weapon.create(name: "T-95 LSW", primary: true)
Weapon.create(name: "TCSG12", primary: true)
Weapon.create(name: "Type-89", primary: true)
Weapon.create(name: "UMP45", primary: true)
Weapon.create(name: "USP40", primary: false)
Weapon.create(name: "V308", primary: true)
Weapon.create(name: "Vector .45 ACP", primary: true)
Weapon.create(name: "552 Commando", primary: true)
Weapon.create(name: "556xi", primary: true)
Weapon.create(name: "6P41", primary: true)
Weapon.create(name: "PRB92", primary: false)
Weapon.create(name: "9mm C1", primary: true)
Weapon.create(name: "9x19VSN", primary: true)
Weapon.create(name: "ACS12", primary: true)
Weapon.create(name: "AK-12", primary: true)
Weapon.create(name: "AK-74M", primary: true)
Weapon.create(name: "ALDA 5.56", primary: true)
Weapon.create(name: "AR-15.50", primary: true)
Weapon.create(name: "AR33", primary: true)
Weapon.create(name: "ARX200", primary: true)
Weapon.create(name: "AUG A3", primary: true)
Weapon.create(name: "AUG A2", primary: true)
Weapon.create(name: "Bailiff 410", primary: false)
Weapon.create(name: "Ballistic Shield", primary: true)
Weapon.create(name: "Bearing 9", primary: false)
Weapon.create(name: "BOSG.12.2", primary: true)
Weapon.create(name: "C75 Auto", primary: false)
Weapon.create(name: "C7E", primary: true)
Weapon.create(name: "C8-SFW", primary: true)
Weapon.create(name: "CAMRS", primary: true)
Weapon.create(name: "Commando 9", primary: true)
Weapon.create(name: "D-50", primary: false)
Weapon.create(name: "F90", primary: true)
Weapon.create(name: "F2", primary: true)
Weapon.create(name: "5.7 USG", primary: false)
Weapon.create(name: "FMG-9", primary: true)
Weapon.create(name: "FO-12", primary: true)
Weapon.create(name: "G36C", primary: true)
Weapon.create(name: "GSh-18", primary: false)
Weapon.create(name: "G8A1", primary: true)
Weapon.create(name: "ITA12L", primary: true)
Weapon.create(name: "ITA12S", primary: false)
Weapon.create(name: "K1A", primary: true)
Weapon.create(name: "Keratos .357", primary: false)
Weapon.create(name: "L85A2", primary: true)
Weapon.create(name: "LFP586", primary: false)
Weapon.create(name: "LMG-E", primary: true)


n1 = User.create(username: "hal", password_digest: "to")